In [1]:
import numpy as np

In [2]:
# ways to reshaping array

In [3]:
arr1=np.arange(6,12).reshape(3,2)
arr1

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
arr1.ravel()   # it will convert higher diamen array into 1D

array([ 6,  7,  8,  9, 10, 11])

In [5]:
arr1

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
b=arr1.transpose()  # row=>colums colums=>rows

In [16]:
b

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [17]:
arr2= np.arange(12,18).reshape(2,3)

In [18]:
arr2

array([[12, 13, 14],
       [15, 16, 17]])

In [24]:
arr3=np.arange(6).reshape(2,3)

In [25]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [30]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [32]:
# fansy indexing

In [34]:
arr4= np.arange(24).reshape(6,4)

In [35]:
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
arr4[[0,2,4]] # passing index as argument it will give those particluar rows

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])