In [1]:
import numpy as np

In [4]:
arr= np.random.randint(low=1,high=100,size=20).reshape(4,5)

In [5]:
arr

array([[28, 25, 60, 63, 80],
       [48, 93, 52, 53, 85],
       [57, 62, 57, 44, 54],
       [ 5, 67, 96, 52, 41]], dtype=int32)

In [7]:
arr[0][2]

np.int32(60)

In [ ]:
# indexing using boolean arrays

In [9]:
arr[arr>50]  # it will give only those elem which are greater than 50 

array([60, 63, 80, 93, 52, 53, 85, 57, 62, 57, 54, 67, 96, 52],
      dtype=int32)

In [10]:
 arr[(arr>50) & (arr %2 !=2)] # greater tahn 50 and also odd

array([60, 63, 80, 93, 52, 53, 85, 57, 62, 57, 54, 67, 96, 52],
      dtype=int32)

In [11]:
 arr[(arr>50) & (arr %2 !=2)] =0 # it will give zero where the condition is true 

In [12]:
arr

array([[28, 25,  0,  0,  0],
       [48,  0,  0,  0,  0],
       [ 0,  0,  0, 44,  0],
       [ 5,  0,  0,  0, 41]], dtype=int32)