In [1]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [4]:
arr1-arr2          # element wise subtraction

array([-3, -3, -3, -3, -3, -3])

In [5]:
 arr1* arr2   # elemetwise multilplication     (vector multiplication)

array([ 4, 10, 18, 28, 40, 54])

In [6]:
arr1* 3   # each ele is muiltipied by 3-- scalar multiplication

array([ 3,  6,  9, 12, 15, 18])

In [10]:
arr2>4  # check each elem is greter thanv4 or not

array([False,  True,  True,  True,  True,  True])

In [12]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [15]:
arr3.dot(arr4)
# dot poroduct

array([[ 28,  31],
       [100, 112]])

In [16]:
arr1.dot(arr2)

np.int64(154)

In [17]:
arr4.max()  # max value in arr4

np.int64(11)

In [18]:
arr4.min()  # min vale

np.int64(6)

In [19]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
arr4.min(axis=0)   # it give min value colums wise axis=0

array([6, 7])

In [21]:
arr4.min(axis=1)  # it give min value row wise 

array([ 6,  8, 10])

In [22]:
arr4.sum()

np.int64(51)

In [23]:
arr4.sum(axis=0)   # colum wise sum

array([24, 27])

In [24]:
arr4.sum(axis=1)  # row wise sum

array([13, 17, 21])

In [25]:
arr4.mean()

np.float64(8.5)

In [26]:
arr4.mean(axis=0)

array([8., 9.])

In [27]:
arr4.mean(axis=1)

array([ 6.5,  8.5, 10.5])

In [28]:
arr4.std()   # gives standard deviation of array

np.float64(1.707825127659933)

In [29]:
arr4.std(axis=0)  # colums wise SD

array([1.63299316, 1.63299316])

In [30]:
arr4.std(axis=1)  # row wise SD

array([0.5, 0.5, 0.5])

In [31]:
np.sin(arr4)  # calculates the sine value of each element in a NumPy array.

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [32]:
np.median(arr4)

np.float64(8.5)

In [33]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [34]:
np.log(arr4)

array([[1.79175947, 1.94591015],
       [2.07944154, 2.19722458],
       [2.30258509, 2.39789527]])

In [35]:
np.tan(arr4)

array([[  -0.29100619,    0.87144798],
       [  -6.79971146,   -0.45231566],
       [   0.64836083, -225.95084645]])

In [36]:
np.cos(arr4)

array([[ 0.96017029,  0.75390225],
       [-0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ]])