In [3]:
'''
numpy == n diamensioanl array
1.numpy is a low level library written in c and fortran for high level
mathematical fucntion. 
2.numpy cleverly overcomes problem of running slower algotithm
on pyhton using multidimensioanl arrays and fucntions that operates on arrray

applications =
1.a powerfull N dimensional array object
2. sohisticated fun(broadcatsing)
3. tools for integrating c /c++ and fortran code
4.  ueful in liner algrebra ,fourier transformation 

properties  of numpy =
1. homogenous
2. only be numbers(numbers,float,complex)
3. fixed item size
'''

'\nnumpy == n diamensioanl array\n1.numpy is a low level library written in c and fortran for high level\nmathematical fucntion. \n2.numpy cleverly overcomes problem of running slower algotithm\non pyhton using multidimensioanl arrays and fucntions that operates on arrray\n\napplications =\n1.a powerfull N dimensional array object\n2. sohisticated fun(broadcatsing)\n3. tools for integrating c /c++ and fortran code\n4.  ueful in liner algrebra ,fourier transformation \n\nproperties  of numpy =\n1. homogenous\n2. only be numbers(numbers,float,complex)\n3. fixed item size\n'

In [4]:
# creating numpy  // n d array
import numpy as np

In [5]:
arr1= np.array([1,2,3,4,5]) # creating array using array function
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)   

numpy.ndarray

In [7]:
arr2= np.array([[1,2,3] ,[4,5,6]]) # matrix form
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3= np.zeros((2,3)) # 2rows 3 colums
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4= np.ones((3,3)) # 3 rows 3 colums
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr5=np.identity(5) #  create an identity matrix 
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
arr6= np.arange(10) #  array of numbers from 0 to 10-1
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr7= np.arange(5,16) # array of numbers from 5 to 16-1
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
arr8 =np.arange(5,16,2) # 2 is gap parameter
arr8

array([ 5,  7,  9, 11, 13, 15])

In [15]:
arr9= np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [16]:
arr10=arr9.copy()
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])