In [2]:
import numpy as np


In [3]:
arr1=np.arange(24)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
arr2=arr1.reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
arr3= arr1.reshape(8,3)
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
arr3[3]

array([ 9, 10, 11])

In [11]:
arr3[:2]  # it  gives 0th and 1st row

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
arr3[:,2]  # 2nd colum of matrix

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [14]:
arr3[:,0:2] # it gives 0st and 1nd colums

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16],
       [18, 19],
       [21, 22]])

In [18]:
# include which rows you want and tehn colums
arr2[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [19]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
for i in arr2:  #Iterates Over rows
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [24]:
for i in np.nditer(arr2):    
    print(i)

 #iterate through every element of a NumPy array, regardless of its dimensions.   

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
