In [2]:
import numpy as np


In [3]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr1.shape  # Returns the shape of the array.

(5,)

In [6]:
arr2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
arr2.shape   # 2 row 2 column 2 matrix 

(2, 2, 2)

In [8]:
arr2.ndim   # diamnesion of array

3

In [9]:
arr1.size   #  total numbers of elemenst

5

In [11]:
 arr2.size


8

In [12]:
arr2.itemsize # Memory occupied by one element (in bytes)

8

In [13]:
arr1.dtype  # datatype of array elements

dtype('int64')

In [14]:
arr1.astype('float')  # converting int data into float data of array element

array([1., 2., 3., 4., 5.])

In [15]:
arr1.itemsize


8